export interface ScenarioSeedInput {
  id: string;
  title: string;
  description: string;
  category: 'daily_life' | 'social' | 'academic' | 'travel' | 'business' | 'free_chat';
  characterRole: string;
  scene: string;
  suggestedVocab: string[];
}

export const SCENARIO_SEEDS: ScenarioSeedInput[] = [
  // ── Daily life (18) ──
  {
    id: 'daily-restaurant',
    title: 'Ordering at a Restaurant',
    description: 'Order food, ask about recommendations, and pay the bill.',
    category: 'daily_life',
    characterRole: 'a friendly waiter at a casual American diner',
    scene: 'The customer is ordering lunch at a busy neighborhood diner.',
    suggestedVocab: ['menu', 'order', 'bill', 'tip', 'specials'],
  },
  {
    id: 'daily-supermarket',
    title: 'Supermarket Shopping',
    description: 'Find products, ask about prices, and check out.',
    category: 'daily_life',
    characterRole: 'a helpful supermarket clerk in the produce aisle',
    scene: 'Shopping for groceries and asking about products, prices, and locations.',
    suggestedVocab: ['aisle', 'checkout', 'receipt', 'organic', 'on sale'],
  },
  {
    id: 'daily-doctor',
    title: 'Doctor Visit',
    description: 'Describe symptoms and answer the doctor\'s questions.',
    category: 'daily_life',
    characterRole: 'a general practitioner at a neighborhood clinic',
    scene: 'A routine patient visit describing symptoms and medical history.',
    suggestedVocab: ['symptom', 'prescription', 'allergy', 'appointment', 'fever'],
  },
  {
    id: 'daily-directions',
    title: 'Asking for Directions',
    description: 'Ask a local for directions and transportation options.',
    category: 'daily_life',
    characterRole: 'a local resident walking on the street',
    scene: 'Asking for directions to a nearby place you cannot find.',
    suggestedVocab: ['block', 'turn left', 'subway', 'straight ahead', 'landmark'],
  },
  {
    id: 'daily-bank',
    title: 'Banking Services',
    description: 'Open an account, transfer money, or ask about services.',
    category: 'daily_life',
    characterRole: 'a bank customer service representative at the front desk',
    scene: 'Visiting a bank branch to open an account and ask about banking options.',
    suggestedVocab: ['account', 'transfer', 'balance', 'interest rate', 'deposit'],
  },
  {
    id: 'daily-apartment',
    title: 'Apartment Viewing',
    description: 'Tour a rental unit and discuss lease terms and utilities.',
    category: 'daily_life',
    characterRole: 'a rental property agent showing an apartment',
    scene: 'Viewing an apartment and discussing rent, deposit, and move-in details.',
    suggestedVocab: ['lease', 'deposit', 'utilities', 'furnished', 'move-in'],
  },
  {
    id: 'daily-hair-salon',
    title: 'Hair Salon Appointment',
    description: 'Book a haircut and explain the style you want.',
    category: 'daily_life',
    characterRole: 'a hairstylist at a local salon',
    scene: 'Getting a haircut and discussing length, style, and preferences.',
    suggestedVocab: ['trim', 'layers', 'appointment', 'blow-dry', 'shampoo'],
  },
  {
    id: 'daily-post-office',
    title: 'Post Office Visit',
    description: 'Mail a package, buy stamps, and ask about delivery options.',
    category: 'daily_life',
    characterRole: 'a postal clerk at the counter',
    scene: 'Sending a package domestically and asking about shipping times and costs.',
    suggestedVocab: ['stamp', 'tracking', 'priority mail', 'package', 'address'],
  },
  {
    id: 'daily-gym',
    title: 'Gym Membership',
    description: 'Sign up for a membership and ask about classes and equipment.',
    category: 'daily_life',
    characterRole: 'a front desk staff member at a fitness center',
    scene: 'Inquiring about gym membership plans, classes, and facility rules.',
    suggestedVocab: ['membership', 'trial', 'locker', 'personal trainer', 'class schedule'],
  },
  {
    id: 'daily-coffee-shop',
    title: 'Coffee Shop Order',
    description: 'Order a drink, customize it, and pay at a cafe.',
    category: 'daily_life',
    characterRole: 'a barista at a busy coffee shop',
    scene: 'Ordering coffee and a snack during the morning rush.',
    suggestedVocab: ['latte', 'size', 'to go', 'extra shot', 'receipt'],
  },
  {
    id: 'daily-pharmacy',
    title: 'Pharmacy Pickup',
    description: 'Pick up a prescription and ask about dosage or alternatives.',
    category: 'daily_life',
    characterRole: 'a pharmacist at a community pharmacy',
    scene: 'Picking up a prescription and asking about side effects and instructions.',
    suggestedVocab: ['prescription', 'dosage', 'refill', 'generic', 'insurance'],
  },
  {
    id: 'daily-laundry',
    title: 'Laundromat Help',
    description: 'Use self-service machines and ask for help with stains or settings.',
    category: 'daily_life',
    characterRole: 'a laundromat attendant on duty',
    scene: 'Doing laundry at a laundromat and asking how to use the machines.',
    suggestedVocab: ['washer', 'dryer', 'detergent', 'cycle', 'quarters'],
  },
  {
    id: 'daily-pet-store',
    title: 'Pet Store Visit',
    description: 'Buy pet supplies and ask for care advice.',
    category: 'daily_life',
    characterRole: 'a knowledgeable pet store associate',
    scene: 'Shopping for pet food and asking about care recommendations.',
    suggestedVocab: ['leash', 'food bowl', 'grooming', 'breed', 'treats'],
  },
  {
    id: 'daily-car-repair',
    title: 'Car Repair Shop',
    description: 'Describe a car problem and discuss repair options and cost.',
    category: 'daily_life',
    characterRole: 'an auto mechanic at a repair shop',
    scene: 'Bringing a car in for a strange noise and discussing repair estimates.',
    suggestedVocab: ['estimate', 'brake', 'oil change', 'diagnostic', 'warranty'],
  },
  {
    id: 'daily-library-card',
    title: 'Library Card Registration',
    description: 'Apply for a library card and learn about borrowing rules.',
    category: 'daily_life',
    characterRole: 'a public library circulation desk clerk',
    scene: 'Signing up for a library card and asking about borrowing limits.',
    suggestedVocab: ['library card', 'due date', 'renew', 'hold', 'fine'],
  },
  {
    id: 'daily-drive-through',
    title: 'Drive-Through Order',
    description: 'Place a fast-food order through the drive-through speaker.',
    category: 'daily_life',
    characterRole: 'a drive-through cashier taking orders',
    scene: 'Ordering a meal at a fast-food drive-through window.',
    suggestedVocab: ['combo', 'combo meal', 'pull forward', 'receipt', 'customize'],
  },
  {
    id: 'daily-neighbor',
    title: 'Talking to a Neighbor',
    description: 'Make small talk and discuss community or building matters.',
    category: 'daily_life',
    characterRole: 'a friendly neighbor in your apartment building',
    scene: 'Running into a neighbor in the hallway and making casual conversation.',
    suggestedVocab: ['noise', 'package', 'community', 'recycling', 'weekend plans'],
  },
  {
    id: 'daily-returns',
    title: 'Returning a Purchase',
    description: 'Return an item, explain the reason, and request a refund or exchange.',
    category: 'daily_life',
    characterRole: 'a customer service associate at a retail store',
    scene: 'Returning a defective product and asking for a refund or exchange.',
    suggestedVocab: ['refund', 'receipt', 'exchange', 'defective', 'return policy'],
  },

  // ── Social (18) ──
  {
    id: 'social-meet',
    title: 'Meeting Someone New',
    description: 'Introduce yourself, share interests, and break the ice.',
    category: 'social',
    characterRole: 'a new acquaintance at a casual community meetup',
    scene: 'Meeting someone new at a local event and starting a conversation.',
    suggestedVocab: ['hobby', 'nice to meet you', 'where are you from', 'work', 'weekend'],
  },
  {
    id: 'social-party',
    title: 'Party Small Talk',
    description: 'Chat casually at a social gathering and keep the conversation going.',
    category: 'social',
    characterRole: 'a friendly guest at a house party',
    scene: 'Making small talk with other guests at a weekend party.',
    suggestedVocab: ['host', 'mutual friend', 'catch up', 'fun', 'music'],
  },
  {
    id: 'social-apology',
    title: 'Apologizing',
    description: 'Apologize for being late or making a mistake and explain why.',
    category: 'social',
    characterRole: 'a friend who was affected by your mistake',
    scene: 'Apologizing sincerely for being late or canceling plans last minute.',
    suggestedVocab: ['sorry', 'my fault', 'misunderstanding', 'make it up', 'excuse'],
  },
  {
    id: 'social-invite',
    title: 'Inviting a Friend',
    description: 'Invite a friend to dinner, an event, or a weekend activity.',
    category: 'social',
    characterRole: 'a close friend you want to hang out with',
    scene: 'Inviting a friend to join you for dinner or an event this weekend.',
    suggestedVocab: ['join us', 'free time', 'RSVP', 'hang out', 'plan'],
  },
  {
    id: 'social-phone',
    title: 'Phone Conversation',
    description: 'Make a phone call to book, confirm, or leave a message.',
    category: 'social',
    characterRole: 'a receptionist answering the phone',
    scene: 'Calling to book an appointment and confirming the details.',
    suggestedVocab: ['hold on', 'leave a message', 'callback', 'available', 'confirm'],
  },
  {
    id: 'social-compliment',
    title: 'Compliments and Thanks',
    description: 'Express gratitude, give compliments, and respond politely.',
    category: 'social',
    characterRole: 'a colleague who recently helped you',
    scene: 'Thanking someone for their help and responding to a compliment.',
    suggestedVocab: ['appreciate', 'grateful', 'kind of you', 'compliment', 'means a lot'],
  },
  {
    id: 'social-decline',
    title: 'Declining an Invitation',
    description: 'Politely say no to plans while keeping the relationship positive.',
    category: 'social',
    characterRole: 'a friend who invited you to an event',
    scene: 'Politely declining an invitation because you are unavailable.',
    suggestedVocab: ['unfortunately', 'rain check', 'another time', 'busy', 'thanks for asking'],
  },
  {
    id: 'social-housewarming',
    title: 'Housewarming Party',
    description: 'Congratulate someone on their new home and chat with guests.',
    category: 'social',
    characterRole: 'the host of a housewarming party',
    scene: 'Attending a housewarming party and complimenting the new home.',
    suggestedVocab: ['congratulations', 'cozy', 'neighborhood', 'housewarming gift', 'tour'],
  },
  {
    id: 'social-dating',
    title: 'Casual Date Conversation',
    description: 'Talk about interests, backgrounds, and light personal topics.',
    category: 'social',
    characterRole: 'someone you are meeting for a casual first date',
    scene: 'Having coffee on a first date and getting to know each other.',
    suggestedVocab: ['interests', 'background', 'weekend', 'travel', 'fun fact'],
  },
  {
    id: 'social-condolence',
    title: 'Expressing Sympathy',
    description: 'Offer condolences and supportive words to someone going through loss.',
    category: 'social',
    characterRole: 'a friend who recently lost a loved one',
    scene: 'Offering sympathy and gentle support to a grieving friend.',
    suggestedVocab: ['condolences', 'thinking of you', 'support', 'difficult time', 'here for you'],
  },
  {
    id: 'social-disagreement',
    title: 'Polite Disagreement',
    description: 'Express a different opinion respectfully without escalating tension.',
    category: 'social',
    characterRole: 'a friend discussing a topic you disagree on',
    scene: 'Discussing a controversial topic and disagreeing politely.',
    suggestedVocab: ['I see your point', 'respectfully', 'perspective', 'fair enough', 'agree to disagree'],
  },
  {
    id: 'social-reunion',
    title: 'Catching Up with an Old Friend',
    description: 'Reconnect after a long time and share life updates.',
    category: 'social',
    characterRole: 'an old friend you have not seen in years',
    scene: 'Meeting an old friend for coffee and catching up on life changes.',
    suggestedVocab: ['long time', 'how have you been', 'remember when', 'update', 'keep in touch'],
  },
  {
    id: 'social-wedding',
    title: 'Wedding Small Talk',
    description: 'Chat with other guests at a wedding reception.',
    category: 'social',
    characterRole: 'another guest seated at your table at a wedding',
    scene: 'Making conversation with fellow guests during a wedding reception.',
    suggestedVocab: ['ceremony', 'beautiful couple', 'how do you know', 'toast', 'reception'],
  },
  {
    id: 'social-gift',
    title: 'Giving and Receiving Gifts',
    description: 'Give a gift graciously or respond warmly when receiving one.',
    category: 'social',
    characterRole: 'a friend celebrating a birthday',
    scene: 'Giving a birthday gift and reacting to receiving one in return.',
    suggestedVocab: ['thoughtful', 'you shouldn\'t have', 'unwrap', 'surprise', 'thank you'],
  },
  {
    id: 'social-advice',
    title: 'Asking a Friend for Advice',
    description: 'Share a problem and ask for a friend\'s perspective or suggestion.',
    category: 'social',
    characterRole: 'a trusted friend you confide in',
    scene: 'Asking a close friend for advice about a personal decision.',
    suggestedVocab: ['what would you do', 'honest opinion', 'dilemma', 'perspective', 'support'],
  },
  {
    id: 'social-farewell',
    title: 'Saying Goodbye',
    description: 'Say farewell before someone moves away or you relocate.',
    category: 'social',
    characterRole: 'a coworker who is moving to another city',
    scene: 'Saying goodbye to a friend or colleague who is relocating.',
    suggestedVocab: ['farewell', 'keep in touch', 'new chapter', 'visit', 'best wishes'],
  },
  {
    id: 'social-introduction',
    title: 'Introducing Two People',
    description: 'Introduce friends or colleagues and help them start talking.',
    category: 'social',
    characterRole: 'a mutual friend you are introducing someone to',
    scene: 'Introducing two people who have not met and facilitating small talk.',
    suggestedVocab: ['meet', 'this is', 'mutual friend', 'in common', 'introduce'],
  },
  {
    id: 'social-volunteer',
    title: 'Volunteer Event Chat',
    description: 'Talk with other volunteers while working on a community project.',
    category: 'social',
    characterRole: 'a fellow volunteer at a community cleanup event',
    scene: 'Chatting with other volunteers during a neighborhood cleanup day.',
    suggestedVocab: ['volunteer', 'community', 'sign up', 'teamwork', 'make a difference'],
  },

  // ── Academic (18) ──
  {
    id: 'academic-class',
    title: 'Asking Questions in Class',
    description: 'Raise your hand, ask for clarification, and request repetition.',
    category: 'academic',
    characterRole: 'a supportive university lecturer',
    scene: 'A lecture where the student asks questions about the material.',
    suggestedVocab: ['clarify', 'repeat', 'homework', 'chapter', 'office hours'],
  },
  {
    id: 'academic-library',
    title: 'Using the Library',
    description: 'Borrow books, search databases, and reserve a study room.',
    category: 'academic',
    characterRole: 'a university librarian at the help desk',
    scene: 'Borrowing books and asking about library resources and study spaces.',
    suggestedVocab: ['due date', 'renew', 'reference', 'database', 'study room'],
  },
  {
    id: 'academic-group',
    title: 'Group Project Meeting',
    description: 'Share ideas, divide tasks, and agree on deadlines.',
    category: 'academic',
    characterRole: 'a fellow student on your group project team',
    scene: 'A group project meeting to divide tasks and set deadlines.',
    suggestedVocab: ['deadline', 'divide tasks', 'presentation', 'research', 'feedback'],
  },
  {
    id: 'academic-application',
    title: 'Application Inquiry',
    description: 'Ask about scholarship, program, or admission requirements.',
    category: 'academic',
    characterRole: 'an admissions office counselor',
    scene: 'Asking about scholarship and graduate program application requirements.',
    suggestedVocab: ['application', 'deadline', 'requirement', 'recommendation', 'essay'],
  },
  {
    id: 'academic-advisor',
    title: 'Meeting Your Academic Advisor',
    description: 'Discuss course selection, credits, and academic progress.',
    category: 'academic',
    characterRole: 'your assigned academic advisor',
    scene: 'Meeting with an advisor about course selection and degree progress.',
    suggestedVocab: ['thesis', 'elective', 'credit', 'proposal', 'semester'],
  },
  {
    id: 'academic-event',
    title: 'Campus Club Event',
    description: 'Join a club event, sign up, and talk with other members.',
    category: 'academic',
    characterRole: 'a student club organizer at an info booth',
    scene: 'Signing up for a campus club and learning about upcoming events.',
    suggestedVocab: ['sign up', 'membership', 'volunteer', 'event', 'club'],
  },
  {
    id: 'academic-lab',
    title: 'Lab Partner Discussion',
    description: 'Coordinate an experiment and discuss methods and results.',
    category: 'academic',
    characterRole: 'your lab partner in a science course',
    scene: 'Working with a lab partner to set up an experiment and record results.',
    suggestedVocab: ['hypothesis', 'procedure', 'measurement', 'variable', 'data'],
  },
  {
    id: 'academic-presentation',
    title: 'Class Presentation Q&A',
    description: 'Present your topic and answer questions from classmates.',
    category: 'academic',
    characterRole: 'a classmate asking questions after your presentation',
    scene: 'Giving a short presentation and answering follow-up questions.',
    suggestedVocab: ['slide', 'conclusion', 'question', 'source', 'summary'],
  },
  {
    id: 'academic-tutoring',
    title: 'Tutoring Session',
    description: 'Get help understanding a difficult concept or assignment.',
    category: 'academic',
    characterRole: 'a peer tutor at the campus tutoring center',
    scene: 'A one-on-one tutoring session for a challenging course topic.',
    suggestedVocab: ['concept', 'example', 'practice problem', 'explain', 'understand'],
  },
  {
    id: 'academic-debate',
    title: 'Classroom Debate',
    description: 'Present an argument and respond to counterpoints in a seminar.',
    category: 'academic',
    characterRole: 'a classmate with an opposing viewpoint in a seminar',
    scene: 'Participating in a structured classroom debate on an assigned topic.',
    suggestedVocab: ['argument', 'evidence', 'counterpoint', 'rebuttal', 'persuade'],
  },
  {
    id: 'academic-exchange',
    title: 'Study Abroad Office',
    description: 'Ask about exchange programs, visas, and course transfer credits.',
    category: 'academic',
    characterRole: 'a study abroad program coordinator',
    scene: 'Visiting the study abroad office to learn about exchange program options.',
    suggestedVocab: ['exchange', 'host university', 'credit transfer', 'visa', 'semester abroad'],
  },
  {
    id: 'academic-internship',
    title: 'Internship Interview',
    description: 'Interview for a student internship and discuss your qualifications.',
    category: 'academic',
    characterRole: 'a hiring manager interviewing student interns',
    scene: 'Interviewing for a summer internship at a company or research lab.',
    suggestedVocab: ['internship', 'resume', 'qualification', 'availability', 'learning goals'],
  },
  {
    id: 'academic-dorm',
    title: 'Roommate Conversation',
    description: 'Discuss dorm rules, schedules, and shared living arrangements.',
    category: 'academic',
    characterRole: 'your new roommate in the dorm',
    scene: 'Meeting your dorm roommate for the first time and setting expectations.',
    suggestedVocab: ['quiet hours', 'shared space', 'schedule', 'clean up', 'guests'],
  },
  {
    id: 'academic-cafeteria',
    title: 'Dining Hall Chat',
    description: 'Talk with classmates while eating in the campus dining hall.',
    category: 'academic',
    characterRole: 'a classmate you often sit with at lunch',
    scene: 'Casual conversation with classmates over lunch in the dining hall.',
    suggestedVocab: ['midterm', 'professor', 'campus', 'meal plan', 'study group'],
  },
  {
    id: 'academic-office-hours',
    title: 'Professor Office Hours',
    description: 'Visit a professor to ask about assignments, grades, or research.',
    category: 'academic',
    characterRole: 'your course professor during office hours',
    scene: 'Attending office hours to ask about an assignment and course material.',
    suggestedVocab: ['extension', 'rubric', 'feedback', 'research opportunity', 'grade'],
  },
  {
    id: 'academic-peer-review',
    title: 'Peer Review Feedback',
    description: 'Give constructive feedback on a classmate\'s draft paper.',
    category: 'academic',
    characterRole: 'a classmate whose essay draft you are reviewing',
    scene: 'Reviewing a peer\'s essay draft and giving constructive written and oral feedback.',
    suggestedVocab: ['thesis statement', 'structure', 'citation', 'revision', 'constructive'],
  },
  {
    id: 'academic-registration',
    title: 'Course Registration Help',
    description: 'Get help registering for classes and resolving schedule conflicts.',
    category: 'academic',
    characterRole: 'a registrar office staff member',
    scene: 'Visiting the registrar to resolve a course registration or waitlist issue.',
    suggestedVocab: ['prerequisite', 'waitlist', 'section', 'enrollment', 'schedule conflict'],
  },
  {
    id: 'academic-thesis',
    title: 'Thesis Defense Practice',
    description: 'Practice presenting your thesis and answering committee questions.',
    category: 'academic',
    characterRole: 'a faculty advisor helping you prepare for your defense',
    scene: 'A mock thesis defense where you present findings and field questions.',
    suggestedVocab: ['methodology', 'findings', 'literature review', 'defend', 'committee'],
  },

  // ── Travel (18) ──
  {
    id: 'travel-checkin',
    title: 'Airport Check-In',
    description: 'Check in for a flight, select a seat, and check luggage.',
    category: 'travel',
    characterRole: 'an airline check-in agent at the counter',
    scene: 'Checking in for an international flight at the airport.',
    suggestedVocab: ['passport', 'boarding pass', 'luggage', 'window seat', 'gate'],
  },
  {
    id: 'travel-hotel',
    title: 'Hotel Check-In',
    description: 'Check into a hotel and ask about amenities and services.',
    category: 'travel',
    characterRole: 'a hotel front desk receptionist',
    scene: 'Checking into a hotel after a long flight and asking about amenities.',
    suggestedVocab: ['reservation', 'checkout time', 'wifi', 'breakfast', 'room key'],
  },
  {
    id: 'travel-navigation',
    title: 'Tourist Directions',
    description: 'Ask how to reach attractions using public transportation.',
    category: 'travel',
    characterRole: 'a local tour guide near a city center',
    scene: 'Asking how to get to tourist attractions using public transport.',
    suggestedVocab: ['metro', 'ticket', 'platform', 'transfer', 'tourist spot'],
  },
  {
    id: 'travel-car-rental',
    title: 'Car Rental',
    description: 'Rent a car and discuss insurance, mileage, and return rules.',
    category: 'travel',
    characterRole: 'a car rental agent at the airport desk',
    scene: 'Renting a car for a road trip and discussing insurance options.',
    suggestedVocab: ['rental', 'insurance', 'mileage', 'return', 'driver license'],
  },
  {
    id: 'travel-ticket',
    title: 'Attraction Tickets',
    description: 'Buy tickets and ask about hours, discounts, and guided tours.',
    category: 'travel',
    characterRole: 'a ticket booth staff member at a museum',
    scene: 'Buying admission tickets for a museum or popular attraction.',
    suggestedVocab: ['admission', 'student discount', 'audio guide', 'exhibition', 'hours'],
  },
  {
    id: 'travel-lost',
    title: 'Lost and Found',
    description: 'Report a lost item and describe it to staff for recovery.',
    category: 'travel',
    characterRole: 'a lost and found office staff member at the airport',
    scene: 'Reporting a lost bag or phone at the airport lost and found desk.',
    suggestedVocab: ['lost property', 'claim', 'describe', 'report', 'found'],
  },
  {
    id: 'travel-customs',
    title: 'Customs and Immigration',
    description: 'Answer border control questions about your trip and belongings.',
    category: 'travel',
    characterRole: 'a customs and immigration officer at the border',
    scene: 'Going through customs and immigration after an international flight.',
    suggestedVocab: ['purpose of visit', 'declare', 'duration', 'visa', 'nothing to declare'],
  },
  {
    id: 'travel-taxi',
    title: 'Taxi or Ride Share',
    description: 'Give the driver your destination and discuss fare or route.',
    category: 'travel',
    characterRole: 'a taxi driver in an unfamiliar city',
    scene: 'Taking a taxi from the airport to your hotel in a new city.',
    suggestedVocab: ['destination', 'meter', 'traffic', 'receipt', 'drop off'],
  },
  {
    id: 'travel-restaurant',
    title: 'Restaurant Abroad',
    description: 'Order food in a foreign country and ask about local dishes.',
    category: 'travel',
    characterRole: 'a waiter at a local restaurant popular with tourists',
    scene: 'Dining at a local restaurant and trying regional specialties.',
    suggestedVocab: ['local specialty', 'spicy', 'vegetarian', 'recommendation', 'check please'],
  },
  {
    id: 'travel-market',
    title: 'Local Market Shopping',
    description: 'Browse a market, ask prices, and buy souvenirs or snacks.',
    category: 'travel',
    characterRole: 'a vendor at a busy outdoor market',
    scene: 'Shopping at a local market and asking about handmade goods and prices.',
    suggestedVocab: ['how much', 'handmade', 'bargain', 'souvenir', 'cash only'],
  },
  {
    id: 'travel-emergency',
    title: 'Travel Emergency',
    description: 'Seek help for a medical or travel emergency in a foreign country.',
    category: 'travel',
    characterRole: 'a hospital receptionist in a foreign city',
    scene: 'Seeking urgent medical help while traveling abroad.',
    suggestedVocab: ['emergency', 'insurance', 'symptoms', 'pharmacy nearby', 'help'],
  },
  {
    id: 'travel-weather',
    title: 'Planning Around Weather',
    description: 'Ask locals or staff about weather and adjust your travel plans.',
    category: 'travel',
    characterRole: 'a hotel concierge giving local advice',
    scene: 'Asking the concierge about weather and alternative activities for a rainy day.',
    suggestedVocab: ['forecast', 'indoor activity', 'rainy season', 'alternative', 'recommend'],
  },
  {
    id: 'travel-tour',
    title: 'Guided Tour Questions',
    description: 'Join a tour and ask the guide questions about sights and history.',
    category: 'travel',
    characterRole: 'a knowledgeable city tour guide',
    scene: 'On a walking tour asking the guide about landmarks and local history.',
    suggestedVocab: ['landmark', 'history', 'photo stop', 'duration', 'tip'],
  },
  {
    id: 'travel-airbnb',
    title: 'Airbnb Host Communication',
    description: 'Coordinate check-in, house rules, and issues with your host.',
    category: 'travel',
    characterRole: 'your Airbnb host messaging before arrival',
    scene: 'Messaging your host about check-in instructions and house rules.',
    suggestedVocab: ['check-in code', 'house rules', 'parking', 'wifi password', 'checkout'],
  },
  {
    id: 'travel-train',
    title: 'Train Station Help',
    description: 'Buy train tickets, find your platform, and ask about connections.',
    category: 'travel',
    characterRole: 'a ticket agent at a busy train station',
    scene: 'Buying train tickets and asking about platforms and transfer times.',
    suggestedVocab: ['platform', 'one-way', 'round trip', 'departure', 'connection'],
  },
  {
    id: 'travel-border',
    title: 'Border Crossing Questions',
    description: 'Ask about documents and procedures when crossing a border by land.',
    category: 'travel',
    characterRole: 'a border checkpoint officer',
    scene: 'Crossing a land border and answering routine entry questions.',
    suggestedVocab: ['passport control', 'entry stamp', 'length of stay', 'documents', 'inspection'],
  },
  {
    id: 'travel-souvenir',
    title: 'Buying Souvenirs',
    description: 'Shop for gifts and ask about shipping or tax-free options.',
    category: 'travel',
    characterRole: 'a shop assistant at a souvenir store',
    scene: 'Buying souvenirs and gifts before returning home from a trip.',
    suggestedVocab: ['souvenir', 'gift wrap', 'tax-free', 'postcard', 'local craft'],
  },
  {
    id: 'travel-delay',
    title: 'Flight Delay at the Gate',
    description: 'Ask airline staff about delays, rebooking, and compensation.',
    category: 'travel',
    characterRole: 'an airline gate agent announcing a delay',
    scene: 'Your flight is delayed and you need information about the new departure time.',
    suggestedVocab: ['delay', 'rebook', 'voucher', 'estimated departure', 'connecting flight'],
  },

  // ── Business (18) ──
  {
    id: 'business-interview',
    title: 'Job Interview',
    description: 'Introduce yourself and answer common interview questions.',
    category: 'business',
    characterRole: 'an HR recruiter conducting a job interview',
    scene: 'A formal job interview for a professional position.',
    suggestedVocab: ['experience', 'strength', 'teamwork', 'background', 'role'],
  },
  {
    id: 'business-meeting',
    title: 'Team Meeting',
    description: 'Participate in a meeting, share updates, and agree on next steps.',
    category: 'business',
    characterRole: 'a team lead running a weekly status meeting',
    scene: 'A team meeting discussing project updates and action items.',
    suggestedVocab: ['agenda', 'action item', 'update', 'deadline', 'follow up'],
  },
  {
    id: 'business-client-call',
    title: 'Client Phone Call',
    description: 'Handle a client inquiry or issue over the phone professionally.',
    category: 'business',
    characterRole: 'a client calling about a service issue',
    scene: 'Taking a client call about a product issue and proposing next steps.',
    suggestedVocab: ['inquiry', 'resolve', 'follow up', 'timeline', 'satisfaction'],
  },
  {
    id: 'business-presentation',
    title: 'Product Demo',
    description: 'Present a product to a client and answer their questions.',
    category: 'business',
    characterRole: 'a potential client attending your product demo',
    scene: 'Demonstrating a product feature set and handling client questions.',
    suggestedVocab: ['feature', 'benefit', 'demo', 'pricing', 'competitive'],
  },
  {
    id: 'business-complaint',
    title: 'Handling a Complaint',
    description: 'Listen to a customer complaint and offer a fair solution.',
    category: 'business',
    characterRole: 'an upset customer with a service complaint',
    scene: 'Professionally handling a customer complaint and de-escalating the situation.',
    suggestedVocab: ['apologize', 'solution', 'refund', 'escalate', 'resolve'],
  },
  {
    id: 'business-networking',
    title: 'Networking Event',
    description: 'Introduce yourself, exchange contacts, and explore opportunities.',
    category: 'business',
    characterRole: 'a professional at an industry networking event',
    scene: 'Networking at an industry conference and exchanging business cards.',
    suggestedVocab: ['connect', 'industry', 'collaborate', 'LinkedIn', 'opportunity'],
  },
  {
    id: 'business-negotiation',
    title: 'Salary Negotiation',
    description: 'Discuss compensation, benefits, and start date with HR.',
    category: 'business',
    characterRole: 'an HR manager discussing a job offer',
    scene: 'Negotiating salary and benefits after receiving a job offer.',
    suggestedVocab: ['offer', 'benefits', 'counteroffer', 'start date', 'compensation'],
  },
  {
    id: 'business-onboarding',
    title: 'First Day Onboarding',
    description: 'Meet your team, learn company policies, and ask setup questions.',
    category: 'business',
    characterRole: 'your onboarding buddy on your first day',
    scene: 'Your first day at a new company meeting colleagues and learning procedures.',
    suggestedVocab: ['orientation', 'policy', 'badge', 'payroll', 'team intro'],
  },
  {
    id: 'business-review',
    title: 'Performance Review',
    description: 'Discuss achievements, goals, and feedback with your manager.',
    category: 'business',
    characterRole: 'your direct manager during an annual review',
    scene: 'An annual performance review discussing goals and areas for growth.',
    suggestedVocab: ['achievement', 'goal', 'feedback', 'development', 'rating'],
  },
  {
    id: 'business-standup',
    title: 'Daily Standup',
    description: 'Briefly share progress, blockers, and plans in a standup meeting.',
    category: 'business',
    characterRole: 'your scrum master facilitating a daily standup',
    scene: 'A short daily standup where each team member shares their update.',
    suggestedVocab: ['blocker', 'progress', 'today', 'yesterday', 'sprint'],
  },
  {
    id: 'business-followup',
    title: 'Following Up on Email',
    description: 'Follow up politely on an unanswered email or pending decision.',
    category: 'business',
    characterRole: 'a busy colleague you emailed last week',
    scene: 'Following up on an important email that has not received a response.',
    suggestedVocab: ['follow up', 'pending', 'touch base', 'reminder', 'timeline'],
  },
  {
    id: 'business-catering',
    title: 'Ordering Event Catering',
    description: 'Plan catering for a meeting or event and confirm dietary needs.',
    category: 'business',
    characterRole: 'a catering sales representative',
    scene: 'Ordering lunch catering for a team meeting and confirming headcount.',
    suggestedVocab: ['headcount', 'dietary restriction', 'delivery time', 'invoice', 'menu options'],
  },
  {
    id: 'business-expense',
    title: 'Expense Report Discussion',
    description: 'Clarify expense policy and resolve a reimbursement issue.',
    category: 'business',
    characterRole: 'a finance team member reviewing expense reports',
    scene: 'Discussing a rejected expense report and clarifying company policy.',
    suggestedVocab: ['receipt', 'reimbursement', 'policy', 'approval', 'category'],
  },
  {
    id: 'business-remote',
    title: 'Remote Work Check-In',
    description: 'Update your manager on remote work progress and availability.',
    category: 'business',
    characterRole: 'your manager on a weekly remote check-in call',
    scene: 'A one-on-one video call updating your manager on remote work progress.',
    suggestedVocab: ['availability', 'priority', 'sync', 'deliverable', 'time zone'],
  },
  {
    id: 'business-partnership',
    title: 'Partnership Discussion',
    description: 'Explore a potential business partnership and align on terms.',
    category: 'business',
    characterRole: 'a business development contact from another company',
    scene: 'An initial meeting to explore a potential partnership opportunity.',
    suggestedVocab: ['partnership', 'proposal', 'terms', 'synergy', 'next steps'],
  },
  {
    id: 'business-resignation',
    title: 'Giving Notice',
    description: 'Inform your manager you are leaving and discuss transition plans.',
    category: 'business',
    characterRole: 'your manager receiving your resignation notice',
    scene: 'A professional conversation informing your manager that you are resigning.',
    suggestedVocab: ['resignation', 'notice period', 'transition', 'last day', 'handover'],
  },
  {
    id: 'business-supplier',
    title: 'Supplier Negotiation',
    description: 'Negotiate pricing, delivery terms, and contract details with a vendor.',
    category: 'business',
    characterRole: 'a sales representative from a key supplier',
    scene: 'Renegotiating contract terms and pricing with a long-term supplier.',
    suggestedVocab: ['quote', 'lead time', 'bulk discount', 'contract', 'MOQ'],
  },
  {
    id: 'business-conference',
    title: 'Conference Booth Pitch',
    description: 'Pitch your product briefly to visitors at a trade show booth.',
    category: 'business',
    characterRole: 'a curious attendee visiting your trade show booth',
    scene: 'Explaining your product to visitors at a busy industry conference booth.',
    suggestedVocab: ['pitch', 'differentiator', 'demo', 'brochure', 'lead'],
  },

  // ── Free chat (1) ──
  {
    id: 'free-chat',
    title: 'Free Conversation',
    description: 'Practice open-ended English conversation on any topic you choose.',
    category: 'free_chat',
    characterRole: 'a friendly English conversation partner',
    scene: 'An open-ended English conversation on any topic the user chooses.',
    suggestedVocab: ['opinion', 'experience', 'recommend', 'interesting', 'thoughts'],
  },
];
